### ISSUE TITLE
Clear text credentials exposed

### ISSUE THREAD

**Issue by MHedish** [xtreme22886/SmartThings_Unifi-Presence-REST#2]
There are two places the Unifi credentials are exposed (ID and PW).  The full login is being exposed both in the Docker/Terminal logs (STDOUT) and, more disturbingly, in the ST IDE logs.

1: ![image](https://user-images.githubusercontent.com/57190961/72462367-eedc5900-379e-11ea-828a-030ce2725e29.png)

2: 
![image](https://user-images.githubusercontent.com/57190961/72462536-45e22e00-379f-11ea-9906-4ac2f2fcfc53.png)

Rather than remove that line from the logs altogether, how about either a string substitution for the password field to obfuscate it from both logs or just substituting a NUL for the field?

**Comment by xtreme22886** [comment]
I can count on you to find things to be tweaked :)

Things have been updated! Download the new Docker image and ST app and let me know what else you find :).

Should I make changes to the /config API then?

**Comment by MHedish** [comment]
Hey, it's what I do. :)

I'll grab the updates and give 'em a spin.

BTW -- Your handle just clicked with me. I'm 22663. :)

**Comment by MHedish** [comment]
;) Looking good.

**ST:** ![image](https://user-images.githubusercontent.com/57190961/72484231-91adcb00-37d1-11ea-893b-7122641304f2.png)

**STDOUT:** `2020-01-16 00:35:56,stdout,"Received {'st': [{'app_url': ***REDACTED***'unifi': [{'address': '192.168.10.194:8443'}, {'username': 'MHedish'}, {'password': '<password>'}, {'site': 'default'}]} and saved to `config.json`

**Comment by xtreme22886** [comment]
Sweet! Thanks for checking it out.

haha that's awesome! Good eye :)

**Comment by MHedish** [comment]
I'm gonna close this one out since it's fixed.

I can't thank you enough for your quick responses here and for putting this all together.
