### ISSUE TITLE
Excessive Authentication

### ISSUE THREAD

**Issue by MHedish** [xtreme22886/SmartThings_Unifi-Presence-REST#3]
Looking at the USG logs, there are quite a lot of AUTHs going on:

![image](https://user-images.githubusercontent.com/57190961/72758233-3f3d2780-3ba0-11ea-9b33-fe6be5be70ce.png)

That's 12 times a minute (naturally since that's the polling frequency).

I turned **off** logging Admin Login events on the USG for now but that doesn't really work.  Now there's no way to log _unauthorized_ logins.  My log was just filled with these.

I see your logging and out of the API at each CheckPresence.  Could the session be made persistent with a 'remember=true" or, at the very least, just not clear the cookie each check.  [API Doc](https://ubntwiki.com/products/software/unifi-controller/api#controller_endpoints)

Since all this activity is all local, I'm not too worried about the sessions between Docker and the USG being hijacked. 😉 

BTW -- I've been running this for almost a week now, tracking 5 phones.  I have a couple of tweaks for you (besides this one) but it's been really solid so far.

**Comment by xtreme22886** [comment]
Thanks for pushing me to program better! I really do appreciate it :). Please download the new Docker image and let me know if your USG logs are getting a breather now.

I'm anxious to see what else you have for me haha

**Comment by MHedish** [comment]
Seems to be working just fine now.  I've turned the auth alerts back on and all is quiet. :grin:

Thanks again for the quick response.
